on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
  pull_request:
  push:
    branches:
      - '**'

jobs:
  build-macos:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install meson

      - name: Fetch Redex
        run: git clone https://github.com/facebook/redex.git

      - name: Build static binary
        run: ./scripts/build_static_binary.py --jobs=$(sysctl -n hw.ncpu)

      - name: Build pypi package
        run: |
          ./scripts/setup.py \
            --version "${{ github.event.inputs.version }}" \
            --binary mariana-trench-binary \
            --pyredex redex/pyredex \
            build

      - name: Log the output directory
        run: ls -lisah dist

      - uses: actions/upload-artifact@v4
        with:
          name: macos-wheels
          path: dist/
          if-no-files-found: error

  build-ubuntu:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install meson

      - name: Fetch Redex
        run: git clone https://github.com/facebook/redex.git

      - name: Build static binary
        run: ./scripts/build_static_binary.py --jobs=$(nproc)

      - name: Build pypi package
        run: |
          ./scripts/setup.py \
            --version "${{ github.event.inputs.version }}" \
            --binary mariana-trench-binary \
            --pyredex redex/pyredex \
            build

      - name: Log the output directory
        run: ls -lisah dist

      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-wheels
          path: dist/
          if-no-files-found: error
